tnss = {
'быть': ['to be', 'was, were', 'been'],
'бить': ['to beat', 'beat', 'beaten'],
'становиться (ся)': ['to become', 'became', 'become'],
'начинать (ся)': ['to begin', 'began', 'begun'],
'дуть': ['to blow', 'blew', 'blown'],
'ломать': ['to break', 'broke', 'broken'],
'приносить': ['to bring', 'brought', 'brought'],
'строить': ['to build', 'built', 'built'],
'гореть, жечь': ['to burn', 'burnt', 'burnt'],
'покупать': ['to buy', 'bought', 'bought'],
'ловить, поймать': ['to catch', 'caught', 'caught'],
'выбирать': ['to choose', 'chose', 'chosen'],
'приходить': ['to come', 'came', 'come'],
'стоить': ['to cost', 'cost', 'cost'],
'резать': ['to cut', 'cut', 'cut'],
'делать': ['to do', 'did', 'done'],
'тащить; рисовать': ['to draw', 'drew', 'drawn'],
'пить': ['to drink', 'drank', 'drunk'],
'везти': ['to drive', 'drove', 'driven'],
'есть, кушать': ['to eat', 'ate [et]', 'eaten'],
'падать': ['to fall', 'fell', 'fallen'],
'чувствовать (себя)': ['to feel', 'felt', 'felt'],
'бороться': ['to fight', 'fought', 'fought'],
'находить': ['to find', 'found', 'found'],
'летать': ['to fly', 'flew', 'flown'],
'забывать': ['to forget', 'forgot', 'forgotten'],
'получать; становиться': ['to get', 'got', 'got'],
'давать': ['to give', 'gave', 'given'],
'идти, ехать': ['to go', 'went', 'gone'],
'расти, выращивать': ['to grow', 'grew', 'grown'],
'иметь': ['to have', 'had', 'had'],
'слышать': ['to hear', 'heard', 'heard'],
'держать': ['to hold', 'held', 'held'],
'держать, хранить': ['to keep', 'kept', 'kept'],
'знать': ['to know', 'knew', 'known'],
'вести': ['to lead', 'led', 'led'],
'учиться, узнавать': ['to learn', 'learnt, learned', 'learnt, learned'],
'покидать, оставлять': ['to leave', 'left', 'left'],
'давать взаймы': ['to lend', 'lent', 'lent'],
'позволять': ['to let', 'let', 'let'],
'зажигать': ['to light', 'lit', 'lit'],
'терять': ['to lose', 'lost', 'lost'],
'делать, создавать': ['to make', 'made', 'made'],
'значить, иметь в виду': ['to mean', 'meant', 'meant'],
'встречать (ся)': ['to meet', 'met', 'met'],
'класть, ставить': ['to put', 'put', 'put'],
'читать': ['to read', 'read [red]', 'read [red]'],
'звонить, звенеть': ['to ring', 'rang', 'rung'],
'бежать': ['to run', 'ran', 'run'],
'сказать; говорить': ['to say', 'said [sed]', 'said [sed]'],
'видеть': ['to see', 'saw', 'seen'],
'продавать': ['to sell', 'sold', 'sold'],
'посылать, отправлять': ['to send', 'sent', 'sent'],
'помещать, класть': ['to set', 'set', 'set'],
'светить, сиять': ['to shine', 'shone', 'shone'],
'показывать': ['to show', 'showed', 'shown'],
'закрывать': ['to shut', 'shut', 'shut'],
'петь': ['to sing', 'sang', 'sung'],
'сидеть': ['to sit', 'sat', 'sat'],
'спать': ['sleep', 'slept', 'slept'],
'говорить, разговаривать': ['speak', 'spoke', 'spoken'],
'тратить; проводить (время)': ['spend', 'spent', 'spent'],
'стоять': ['stand', 'stood', 'stood'],
'мести, подметать': ['sweep', 'swept', 'swept'],
'плавать': ['swim', 'swam', 'swum']
# 'брать, взять': ['to take', 'took', 'taken'],
# 'учить, обучать': ['to teach', 'taught', 'taught'],
# 'сказать, рассказывать': ['to tell', 'told', 'told'],
# 'думать': ['to think', 'thought', 'thought'],
# 'бросать': ['to throw', 'threw', 'thrown'],
# 'понимать': ['to understand', 'understood', 'understood'],
# 'опрокидывать; срывать (планы)': ['to upset', 'upset', 'upset'],
# 'побеждать; выигрывать': ['to win', 'won', 'won'],
# 'писать': ['to write', 'wrote', 'written'],
}