tnss = {
'быть': ['be', 'was/were', 'been'],
'бить': ['beat', 'beat', 'beaten'],
'становиться (ся)': ['become', 'became', 'become'],
'начинать (ся)': ['begin', 'began', 'begun'],
'дуть': ['blow', 'blew', 'blown'],
'ломать': ['break', 'broke', 'broken'],
'приносить': ['bring', 'brought', 'brought'],
'строить': ['build', 'built', 'built'],
'гореть, жечь': ['burn', 'burnt', 'burnt'],
'покупать': ['buy', 'bought', 'bought'],
'ловить, поймать': ['catch', 'caught', 'caught'],
'выбирать': ['choose', 'chose', 'chosen'],
'приходить': ['come', 'came', 'come'],
'стоить': ['cost', 'cost', 'cost'],
'резать': ['cut', 'cut', 'cut'],
'делать': ['do', 'did', 'done'],
'тащить; рисовать': ['draw', 'drew', 'drawn'],
'пить': ['drink', 'drank', 'drunk'],
'везти': ['drive', 'drove', 'driven'],
'есть, кушать': ['eat', 'ate [et]', 'eaten'],
'падать': ['fall', 'fell', 'fallen'],
'чувствовать (себя)': ['feel', 'felt', 'felt'],
'бороться': ['fight', 'fought', 'fought'],
'находить': ['find', 'found', 'found'],
'летать': ['fly', 'flew', 'flown'],
'забывать': ['forget', 'forgot', 'forgotten'],
'получать': ['get', 'got', 'got'],
'давать': ['give', 'gave', 'given'],
'идти, ехать': ['go', 'went', 'gone'],
'расти, выращивать': ['grow', 'grew', 'grown'],
'иметь': ['have', 'had', 'had'],
'слышать': ['hear', 'heard', 'heard'],
'держать': ['hold', 'held', 'held'],
'держать, хранить': ['keep', 'kept', 'kept'],
'знать': ['know', 'knew', 'known'],
'вести': ['lead', 'led', 'led'],
'учиться, узнавать': ['learn', 'learnt/learned', 'learnt/learned'],
'покидать, оставлять': ['leave', 'left', 'left'],
'давать взаймы': ['lend', 'lent', 'lent'],
'позволять': ['let', 'let', 'let'],
'зажигать': ['light', 'lit', 'lit'],
'терять': ['lose', 'lost', 'lost'],
'делать, создавать': ['make', 'made', 'made'],
'значить, иметь в виду': ['mean', 'meant', 'meant'],
'встречать (ся)': ['meet', 'met', 'met'],
'класть, ставить': ['put', 'put', 'put'],
'читать': ['read', 'read [red]', 'read [red]'],
'звонить, звенеть': ['ring', 'rang', 'rung'],
'бежать': ['run', 'ran', 'run'],
'сказать; говорить': ['say', 'said', 'said'],
'видеть': ['see', 'saw', 'seen'],
'продавать': ['sell', 'sold', 'sold'],
'посылать, отправлять': ['send', 'sent', 'sent'],
'помещать, класть': ['set', 'set', 'set'],
'светить, сиять': ['shine', 'shone', 'shone'],
'показывать': ['show', 'showed', 'shown'],
'закрывать/запирать(окно)': ['shut', 'shut', 'shut'],
'петь': ['sing', 'sang', 'sung'],
'сидеть': ['sit', 'sat', 'sat'],
'спать': ['sleep', 'slept', 'slept'],
'говорить, разговаривать': ['speak', 'spoke', 'spoken'],
'тратить; проводить (время)': ['spend', 'spent', 'spent'],
'стоять': ['stand', 'stood', 'stood'],
'мести, подметать': ['sweep', 'swept', 'swept'],
'плавать': ['swim', 'swam', 'swum'],
'учить, обучать': ['teach', 'taught', 'taught'],
'сказать, рассказывать': ['tell', 'told', 'told'],
'думать': ['think', 'thought', 'thought'],
'брать, взять': ['take', 'took', 'taken'],
'бросать': ['throw', 'threw', 'thrown'],
'понимать': ['understand', 'understood', 'understood'],
'опрокидывать; срывать (планы)': ['upset', 'upset', 'upset'],
'побеждать; выигрывать': ['win', 'won', 'won'],
'писать': ['write', 'wrote', 'written'],
}